const products = [
  {
    _id: '5d1f237e8f3903e269cab399',
    onSale: false,
    price: '$42.09',
    priceSale: '$36.40',
    picture: 'https://picsum.photos/300/300',
    color: 'blue',
    size: 'small',
    name: 'duis do',
    description_short: 'laborum sunt veniam',
    description: 'Id eu laborum sunt laboris pariatur irure laboris velit duis ipsum fugiat. Nisi qui ullamco sunt consectetur fugiat enim occaecat officia est aliquip eu et. Minim elit reprehenderit officia qui Lorem esse laborum in.',
  },
  {
    _id: '5d1f237ea7023f8ca4ecc646',
    onSale: false,
    price: '$37.51',
    priceSale: '$19.60',
    picture: 'https://picsum.photos/300/300',
    color: 'green',
    size: 'small',
    name: 'ut consectetur',
    description_short: 'Lorem ex mollit',
    description: 'Sunt ipsum est fugiat dolor veniam quis. Dolore ex do ipsum aliquip Lorem laboris est laboris. Sunt eu do amet non qui irure qui tempor.',
  },
  {
    _id: '5d1f237eeec440b96da41119',
    onSale: true,
    price: '$48.96',
    priceSale: '$26.20',
    picture: 'https://picsum.photos/300/300',
    color: 'blue',
    size: 'large',
    name: 'eiusmod Lorem',
    description_short: 'Lorem officia non',
    description: 'Mollit adipisicing elit occaecat enim nostrud eu proident ea qui amet pariatur. Ea irure aliquip officia enim laboris ipsum officia nostrud. Mollit mollit proident do laborum do duis incididunt anim et.',
  },
  {
    _id: '5d1f237e9e645fcff13af633',
    onSale: true,
    price: '$48.03',
    priceSale: '$25.50',
    picture: 'https://picsum.photos/300/300',
    color: 'green',
    size: 'large',
    name: 'sint duis',
    description_short: 'ea consectetur laboris',
    description: 'Ullamco excepteur Lorem tempor ea minim laborum cillum nulla tempor in anim in. Deserunt aliqua dolore consequat proident amet commodo laboris incididunt nisi ipsum deserunt elit incididunt. Mollit enim excepteur do culpa aliquip sit labore aliquip reprehenderit dolore magna do.',
  },
  {
    _id: '5d1f237e0e1532e507b1b95d',
    onSale: false,
    price: '$85.21',
    priceSale: '$22.90',
    picture: 'https://picsum.photos/300/300',
    color: 'green',
    size: 'large',
    name: 'dolor commodo',
    description_short: 'occaecat elit nostrud',
    description: 'Cillum magna sunt quis esse aliquip ex esse nostrud elit aute ut. Officia amet aliqua dolore consequat magna dolor ex veniam enim est deserunt sit exercitation. In duis sit eiusmod veniam pariatur non ex officia velit culpa commodo pariatur nulla aliqua.',
  },
  {
    _id: '5d1f237ebb7b349222f7e49e',
    onSale: true,
    price: '$58.78',
    priceSale: '$51.80',
    picture: 'https://picsum.photos/300/300',
    color: 'purple',
    size: 'medium',
    name: 'mollit ad',
    description_short: 'nostrud adipisicing laboris',
    description: 'Qui commodo nostrud dolor occaecat pariatur fugiat. Veniam tempor duis fugiat velit labore. Proident mollit minim anim tempor cupidatat exercitation ut.',
  },
  {
    _id: '5d1f237e0da2612e2c176f3e',
    onSale: true,
    price: '$50.98',
    priceSale: '$28.90',
    picture: 'https://picsum.photos/300/300',
    color: 'green',
    size: 'large',
    name: 'reprehenderit sunt',
    description_short: 'ullamco cupidatat sit',
    description: 'Culpa dolor cupidatat ex in sint deserunt Lorem irure ipsum nostrud. Do sint adipisicing magna mollit officia et adipisicing ut occaecat occaecat. Sunt deserunt officia aute adipisicing cupidatat eu aliquip.',
  },
  {
    _id: '5d1f237e24716da5d92387f5',
    onSale: false,
    price: '$77.53',
    priceSale: '$35.10',
    picture: 'https://picsum.photos/300/300',
    color: 'blue',
    size: 'large',
    name: 'elit esse',
    description_short: 'ad laboris deserunt',
    description: 'Enim esse reprehenderit sunt consectetur duis aliquip laborum commodo aliqua aliqua aliquip aliqua enim commodo. Adipisicing ut consequat laborum anim. Officia cillum ut quis reprehenderit magna qui anim cillum ex labore.',
  },
  {
    _id: '5d1f237e07e2eacd342607b5',
    onSale: true,
    price: '$44.31',
    priceSale: '$11.70',
    picture: 'https://picsum.photos/300/300',
    color: 'blue',
    size: 'medium',
    name: 'aliquip ex',
    description_short: 'Lorem dolore nostrud',
    description: 'Lorem qui eiusmod nulla est excepteur. Incididunt ut est dolor adipisicing non ad anim eu irure occaecat consectetur. Aliquip tempor ad aliqua magna sit do nisi elit cupidatat ut.',
  },
  {
    _id: '5d1f237e5fa331af0d0975ee',
    onSale: false,
    price: '$43.83',
    priceSale: '$30.90',
    picture: 'https://picsum.photos/300/300',
    color: 'red',
    size: 'small',
    name: 'anim pariatur',
    description_short: 'incididunt culpa fugiat',
    description: 'Velit aute ut consequat ea laboris qui culpa aute veniam. Sint ullamco culpa laborum eu. Id tempor dolor esse dolore consequat ad reprehenderit do minim proident.',
  },
];

export default products;
